#!/bin/bash

# create archive llvm-*.tar.gz which includes LLVM and compiler and runtime
ver=3.4

rm -f *.tar.gz 
rm -rf ./llvm-${ver}*
rm -rf ./clang-${ver}*

# LLVM
wget http://llvm.org/releases/${ver}/llvm-${ver}.src.tar.gz
tar zxf llvm-${ver}.src.tar.gz

# Clang
wget http://llvm.org/releases/${ver}/clang-${ver}.src.tar.gz
tar zxf clang-${ver}.src.tar.gz
/bin/mv clang-${ver} llvm-${ver}/tools/clang

# extra
wget http://llvm.org/releases/${ver}/clang-tools-extra-${ver}.src.tar.gz
tar zxf clang-tools-extra-${ver}.src.tar.gz
/bin/mv clang-tools-extra-${ver} llvm-${ver}/tools/clang/extra

# compiler-rt
wget http://llvm.org/releases/${ver}/compiler-rt-${ver}.src.tar.gz
tar zxf compiler-rt-${ver}.src.tar.gz
/bin/mv compiler-rt-${ver} llvm-${ver}/projects/compiler-rt

# Archive all
rm -f *.tar.gz
tar zcf llvm-${ver}.tar.gz llvm-${ver}
rm -rf ./llvm-${ver}
